### ISSUE TITLE
NPM doesn't work in mage

### ISSUE THREAD

**Issue by JoshuavanGelder** [GrimLink/mage#16]
When i run a npm command i get this error `  Command "npm" is not defined.  `.

**Comment by GrimLink** [comment]
Hi @JoshuavanGelder,

I suspect you are using this for the warden scope.

Mage does not currently offer the ability to run non-Magento 2 commands. However, we could add an option to allow you to run any command using `mage warden`. This would make any npm command possible within warden.

However, it is important to note that using npm within warden is not necessary when using nvm. With nvm, you can manage multiple Node.js versions on your system and use the desired version outside of the warden container.
